{\rtf1\ansi\ansicpg1252\cocoartf2821
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs24 \cf0 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 -- Identifying regions that are net energy producers \
-- This query calculates the total energy surplus by subtracting demand from net generation.\kerning1\expnd0\expndtw0 \outl0\strokewidth0 \
SELECT \
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0
\cf0     region, \
    SUM(net_generation - demand) AS excess_energy\
FROM intel.energy_data\
GROUP BY region\
ORDER BY excess_energy DESC;\
-- The Mid-Atlantic region has the highest excess energy surplus.\
\
-- Total Renewable Energy by Region\
-- This query calculates total renewable energy production per region.\
SELECT \
    region, \
    SUM(hydropower_and_pumped_storage + wind + solar) AS total_renewable_energy\
FROM intel.energy_data\
GROUP BY region\
ORDER BY total_renewable_energy DESC;\
-- The top two regions for renewable energy production: Northwest & Texas.\
\
-- Percentage of Renewable Energy by Region\
-- This query calculates the percentage of energy generation that is renewable.\
SELECT \
    region, \
    SUM(hydropower_and_pumped_storage + wind + solar) AS total_renewable_energy, \
    ROUND((SUM(hydropower_and_pumped_storage + wind + solar) * 100 / SUM(net_generation)), 2) AS renewable_percentage\
FROM intel.energy_data\
GROUP BY region\
ORDER BY renewable_percentage DESC;\
-- The Northwest has the highest percentage of renewable energy.\
\
-- Generating New Data by Energy Type\
-- Renewable Energy Generation\
-- This query calculates renewable energy produced per row.\
SELECT \
    date, \
    region, \
    (hydropower_and_pumped_storage + wind + solar) AS energy_generated_mw\
FROM intel.energy_data;\
\
-- Adding an Energy Type Column for Renewable Energy\
SELECT \
    date, \
    region, \
    (hydropower_and_pumped_storage + wind + solar) AS energy_generated_mw, \
    'renewable energy' AS energy_type\
FROM intel.energy_data;\
\
--  Fossil Fuel Energy Generation\
-- This query calculates fossil fuel energy produced per row.\
SELECT \
    date, \
    region, \
    (all_petroleum_products + coal + natural_gas + nuclear + other_fuel_sources) AS energy_generated_mw\
FROM intel.energy_data;\
\
-- Adding an Energy Type Column for Fossil Fuels\
SELECT \
    date, \
    region, \
    (all_petroleum_products + coal + natural_gas + nuclear + other_fuel_sources) AS energy_generated_mw, \
    'fossil fuel' AS energy_type\
FROM intel.energy_data;\
\
-- Combining Renewable & Fossil Fuel Data\
-- This query merges renewable and fossil fuel energy data using UNION.\
SELECT \
    date, \
    region, \
    (hydropower_and_pumped_storage + wind + solar) AS energy_generated_mw, \
    'renewable energy' AS energy_type\
FROM intel.energy_data\
UNION \
SELECT \
    date, \
    region, \
    (all_petroleum_products + coal + natural_gas + nuclear + other_fuel_sources) AS energy_generated_mw, \
    'fossil fuel' AS energy_type\
FROM intel.energy_data;\
\
-- Aggregating Power Plant Data\
-- Joining Power Plant & Energy Data\
-- This query joins intel.power_plants and intel.energy_by_power_plant on plant_code.\
SELECT \
    pp.*, \
    ebp.*\
FROM intel.power_plants AS pp\
INNER JOIN intel.energy_by_power_plant AS ebp\
ON pp.plant_code = ebp.plant_code;\
\
-- Total Renewable Power Plants by Region\
-- This query counts the number of renewable energy plants per region.\
WITH plant_data AS (\
    SELECT \
        pp.region, \
        pp.plant_code, \
        ebp.energy_type\
    FROM intel.power_plants AS pp\
    INNER JOIN intel.energy_by_power_plant AS ebp\
    ON pp.plant_code = ebp.plant_code\
) \
SELECT \
    region, \
    COUNT(plant_code) AS total_renewable_plants\
FROM plant_data\
WHERE energy_type = 'renewable_energy'\
GROUP BY region\
ORDER BY total_renewable_plants DESC;\
-- The Midwest region has the most renewable power plants.\
\
\
-- Solar Power Plants & Energy Generated by Region\
-- This query calculates solar energy production per region.\
WITH plant_data AS (\
    SELECT \
        pp.region, \
        pp.plant_code, \
        pp.primary_technology, \
        ebp.energy_generated_mw\
    FROM intel.power_plants AS pp\
    INNER JOIN intel.energy_by_power_plant AS ebp\
    ON pp.plant_code = ebp.plant_code\
) \
SELECT \
    plant_data.region, \
    COUNT(plant_data.plant_code) AS total_solar_plants, \
    SUM(plant_data.energy_generated_mw) AS total_solar_energy\
FROM plant_data\
WHERE plant_data.primary_technology = 'Solar Photovoltaic'\
GROUP BY plant_data.region\
ORDER BY total_solar_energy DESC;\
-- Texas generates the most solar energy, followed by California.\
\
-- Filtering Solar Power Plants by Region\
-- This query filters solar power plant counts by regions that have at least 50 plants.\
WITH plant_data AS (\
    SELECT \
        pp.region, \
        pp.plant_code, \
        pp.primary_technology, \
        ebp.energy_generated_mw\
    FROM intel.power_plants AS pp\
    INNER JOIN intel.energy_by_power_plant AS ebp\
    ON pp.plant_code = ebp.plant_code\
) \
SELECT \
    plant_data.region, \
    COUNT(plant_data.plant_code) AS total_solar_plants, \
    SUM(plant_data.energy_generated_mw) AS total_solar_energy\
FROM plant_data\
WHERE plant_data.primary_technology = 'Solar Photovoltaic'\
GROUP BY plant_data.region\
HAVING COUNT(plant_data.plant_code) >= 50\
ORDER BY total_solar_energy DESC;\
-- The Midwest has many solar plants but lower energy output.\
\
\
-- Hourly Trends in Renewable Energy\
-- Renewable Energy Generation by Hour\
-- This query calculates renewable energy production for each hour.\
SELECT \
    region, \
    DATE_PART('hour', time_at_end_of_hour) AS hour, \
    SUM(hydropower_and_pumped_storage + wind + solar) AS total_renewable_energy\
FROM intel.energy_data\
GROUP BY region, hour\
ORDER BY hour, region;\
\
--  Renewable Energy Trends for California & Northwest\
-- This query filters renewable energy trends by region.\
SELECT \
    region, \
    DATE_PART('hour', time_at_end_of_hour) AS hour, \
    SUM(hydropower_and_pumped_storage + wind + solar) AS total_renewable_energy\
FROM intel.energy_data\
WHERE region IN ('California', 'Northwest')\
GROUP BY region, hour\
ORDER BY hour, region;\
-- The Northwest maintains higher energy at night, while California drops after sunset.\
\
}